
services:
  postgres_db:
    image: postgres:13
    environment:
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    networks:
      - my_network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  php-fpm:
    build: .
    volumes:
      - ./:/var/www/html
    networks:
      - my_network
    depends_on:
      - postgres_db

  nginx:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Исправленный путь
      - ./:/var/www/html
    networks:
      - my_network
    depends_on:
      - php-fpm

networks:
  my_network:

volumes:
  postgres-data: